export const ITEM_WIDTH = 'ITEM_WIDTH'
export const ITEM_HEIGHT = 'ITEM_HEIGHT'
export const ITEM_CAPTION = 'ITEM_CAPTION'
export const ITEM_VISIBLE = 'ITEM_VISIBLE'
export const ITEM_NEW = 'ITEM_NEW'